on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
    - docs/**
    - docs.doxygen
    - doxygen-layout.xml
    - README.md
    - github/workflows/main.yml

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: make build dir
        run: |
          mkdir -p build/docs
      - name: Setup Pages
        uses: mattnotmitt/doxygen-action@1.12.0
        with:
          doxyfile-path: docs.doxygen
      - name: Chown user
        run: |
          sudo chown -R $USER:$USER $GITHUB_WORKSPACE
      - name: Setup sitemap.txt
        run: |
          find build/docs/html/ -name "*.html"|sed 's-build/docs/html-https://turnstoneos.com-' > build/docs/html/sitemap.txt
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'build/docs/html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
    
